name: Testing on ubuntu-latest

on: [push, pull_request]

env:
  SKBUILD_CONFIGURE_OPTIONS: -DCMAKE_CXX_FLAGS='-D_GLIBCXX_USE_CXX11_ABI=0'
  SKBUILD_BUILD_OPTIONS: --verbose

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade pip wheel
          pip install -r build_requirements.txt
          pip install -r test_requirements.txt
          echo "SKBUILD_CONFIGURE_OPTIONS=${{ env.SKBUILD_CONFIGURE_OPTIONS }}" >> "$GITHUB_ENV"
          echo "SKBUILD_BUILD_OPTIONS=${{ env.SKBUILD_BUILD_OPTIONS }}" >> "$GITHUB_ENV"

      - name: make
        shell: bash
        run: |
          pip install -v .

      - name: make test
        shell: bash
        run: |
          export CASM_PREFIX=$(python -c 'import site; print(site.getsitepackages()[0])')/libcasm
          echo "CASM_PREFIX: ${CASM_PREFIX}"
          ls -hl ${CASM_PREFIX}/lib
          
          echo "libcasm_global:"
          readelf --dynamic ${CASM_PREFIX}/lib/libcasm_global*
          ldd ${CASM_PREFIX}/lib/libcasm_global*
          
          echo "libcasm_crystallography:"
          readelf --dynamic ${CASM_PREFIX}/lib/libcasm_crystallography*
          ldd ${CASM_PREFIX}/lib/libcasm_crystallography*
          
          echo "libcasm_mapping:"
          readelf --dynamic ${CASM_PREFIX}/lib/libcasm_mapping*
          ldd ${CASM_PREFIX}/lib/libcasm_mapping*
          
          ls -hl ${CASM_PREFIX}/mapping
          ls -hl ${CASM_PREFIX}/mapping/info
          ls -hl ${CASM_PREFIX}/mapping/mapsearch
          ls -hl ${CASM_PREFIX}/mapping/methods
          
          echo "_mapping_info:"
          readelf --dynamic ${CASM_PREFIX}/mapping/info/_mapping_info*
          ldd ${CASM_PREFIX}/mapping/info/_mapping_info*
          
          echo "_mapping_mapsearch:"
          readelf --dynamic ${CASM_PREFIX}/mapping/mapsearch/_mapping_mapsearch*
          ldd ${CASM_PREFIX}/mapping/mapsearch/_mapping_mapsearch*
          
          echo "_mapping_methods:"
          readelf --dynamic ${CASM_PREFIX}/mapping/methods/_mapping_methods*
          ldd ${CASM_PREFIX}/mapping/methods/_mapping_methods*
          
          python -m pytest -rsap python/tests

      - name: Set up doc requirements
        run: |
          pip install -r doc_requirements.txt

      - name: build docs
        shell: bash
        run: |
          cd python/doc
          sphinx-build -b html . _build/html

      - name: upload docs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: libcasm-mapping-docs
          path: python/doc/_build/html
