name: Testing CASM dependencies on ubuntu-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: checkout libcasm-global
        uses: actions/checkout@v3
        with:
          repository: prisms-center/CASMcode_global
          path: CASMcode_global

      - name: checkout libcasm-xtal
        uses: actions/checkout@v3
        with:
          repository: prisms-center/CASMcode_crystallography
          path: CASMcode_crystallography

      - name: checkout libcasm-mapping
        uses: actions/checkout@v3
        with:
          path: CASMcode_mapping

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade pip wheel build

      - name: Install dependencies
        run: |
          cd CASMcode_mapping
          pip install -r build_requirements.txt

      - name: test global
        shell: bash
        run: |
          cd CASMcode_global
          pip install -r test_requirements.txt
          pytest -rsap python/tests

      - name: test xtal
        shell: bash
        run: |
          cd CASMcode_crystallography
          pip install -r test_requirements.txt
          pytest -rsap python/tests
