name: Testing source build using wheels on ubuntu-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: checkout libcasm-global
        uses: actions/checkout@v3
        with:
          repository: prisms-center/CASMcode_global
          path: CASMcode_global

      - name: checkout libcasm-xtal
        uses: actions/checkout@v3
        with:
          repository: prisms-center/CASMcode_crystallography
          path: CASMcode_crystallography
          ref: "2.0a3"

      - name: checkout libcasm-mapping
        uses: actions/checkout@v3
        with:
          path: CASMcode_mapping

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade pip wheel

      - name: build global wheel
        shell: bash
        run: |
          cd CASMcode_global
          git submodule update --init --recursive
          pip install -r build_requirements.txt
          python -m build

      - name: install global wheel
        shell: bash
        run: |
          cd CASMcode_global
          pip install dist/*.whl

      - name: make test global
        shell: bash
        run: |
          cd CASMcode_global
          pip install -r test_requirements.txt
          python -m pytest -rsap python/tests

      - name: build xtal wheel
        shell: bash
        run: |
          cd CASMcode_crystallography
          pip install -r build_requirements.txt
          python -m build

      - name: install xtal wheel
        shell: bash
        run: |
          cd CASMcode_crystallography
          pip install dist/*.whl

      - name: make test xtal
        shell: bash
        run: |
          cd CASMcode_crystallography
          pip install -r test_requirements.txt
          python -m pytest -rsap python/tests

      - name: make mapping
        shell: bash
        run: |
          cd CASMcode_mapping
          pip install -r build_requirements.txt
          pip install -v .

      - name: make test mapping
        shell: bash
        run: |
          cd CASMcode_mapping
          export CASM_PREFIX=$(python -c 'import site; print(site.getsitepackages()[0])')/libcasm
          echo "CASM_PREFIX: ${CASM_PREFIX}"
          ls -hl ${CASM_PREFIX}/lib
          
          echo "libcasm_global:"
          readelf --dynamic ${CASM_PREFIX}/lib/libcasm_global*
          ldd ${CASM_PREFIX}/lib/libcasm_global*
          
          echo "libcasm_crystallography:"
          readelf --dynamic ${CASM_PREFIX}/lib/libcasm_crystallography*
          ldd ${CASM_PREFIX}/lib/libcasm_crystallography*
          
          echo "libcasm_mapping:"
          readelf --dynamic ${CASM_PREFIX}/lib/libcasm_mapping*
          ldd ${CASM_PREFIX}/lib/libcasm_mapping*
          
          ls -hl ${CASM_PREFIX}/mapping
          ls -hl ${CASM_PREFIX}/mapping/info
          ls -hl ${CASM_PREFIX}/mapping/mapsearch
          ls -hl ${CASM_PREFIX}/mapping/methods
          
          echo "_mapping_info:"
          readelf --dynamic ${CASM_PREFIX}/mapping/info/_mapping_info*
          ldd ${CASM_PREFIX}/mapping/info/_mapping_info*
          
          echo "_mapping_mapsearch:"
          readelf --dynamic ${CASM_PREFIX}/mapping/mapsearch/_mapping_mapsearch*
          ldd ${CASM_PREFIX}/mapping/mapsearch/_mapping_mapsearch*
          
          echo "_mapping_methods:"
          readelf --dynamic ${CASM_PREFIX}/mapping/methods/_mapping_methods*
          ldd ${CASM_PREFIX}/mapping/methods/_mapping_methods*
          
          pip install -r test_requirements.txt
          python -m pytest -rsap python/tests

      - name: Set up doc requirements
        run: |
          cd CASMcode_mapping
          pip install -r doc_requirements.txt

      - name: build docs
        shell: bash
        run: |
          cd CASMcode_mapping
          cd python/doc
          sphinx-build -b html . _build/html

      - name: upload docs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: libcasm-mapping-docs
          path: python/doc/_build/html
